### ISSUE TITLE
Upstream SSL certificate verify error on JWT validation

### ISSUE THREAD

**Issue by mixerka** [cloudendpoints/esp#262]
I am using Google Cloud Endpoints with container engine.

My securityDefinition is:
```
  ridero_jwt:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://pg.ridero.store"
    x-google-jwks_uri: "https://pg.ridero.store/auth/certs"
    x-google-audiences: "store-admin-pg"

```
When I am trying to use JWT token, I get the following error in ESP stdout:
```
2017/09/08 04:28:17 [error] 9#9: upstream SSL certificate verify error: (18:self signed certificate)
10.60.3.1 - - [08/Sep/2017:04:28:17 +0000] "POST /v1/sku HTTP/1.0" 401 212 "-" "curl/7.54.0"
```

In response I get:
```
{
 "code": 16,
 "message": "JWT validation failed: Unable to fetch verification key",
 "details": [
  {
   "@type": "type.googleapis.com/google.rpc.DebugInfo",
   "stackEntries": [],
   "detail": "auth"
  }
 ]
}
```

In tracer I get:
![screen shot 2017-09-08 at 09 31 03](https://user-images.githubusercontent.com/3119549/30196231-7b542f1a-9478-11e7-839c-a701535ad11d.png)

I have tried to connect into esp container with "kubectl run", install curl and make request and there was no errors. 
I have checked trusted-ca-certificates.crt and it contains my CA: DST Root CA X3.
I have tried to set  x-google-jwks_uri to http://auth.default.svc.cluster.local/certs, but esp couldn't resolve domain name.
