### ISSUE TITLE
HTTPS client should support SNI

### ISSUE THREAD

**Issue by lizan** [cloudendpoints/esp#271]
The HTTPS client fetching auth public key doesn't support SNI, in some case ESP won't be able to fetch keys. See #262

**Comment by qiwzhang** [comment]
Does Nginx proxy_pass upstream support SNI?   Is this just our "http.cc" code issue or this is the whole Nginx issue?

**Comment by bourquep** [comment]
Any idea when this might be implemented? I'm facing the same situation.

**Comment by lei-tang** [comment]
@bourquep , @MrBlaise , @Daniel-Houston, can you share your configurations and your steps to reproduce the problem? I created a PR https://github.com/cloudendpoints/esp/pull/399 for this problem and I hope to test whether this PR fixes the problem. If you like, you can also try this PR on your end and let me know the result. Thanks!

**Comment by MrBlaise** [comment]
Nothing special configuration, I am doing everything that is written in the Kubernetes Engine tutorial (https://cloud.google.com/endpoints/docs/openapi/get-started-kubernetes-engine) and then set up custom domain according to this: https://cloud.google.com/endpoints/docs/openapi/serving-apis-from-domains I also use auth0 so I followed this guide: https://auth0.com/docs/integrations/google-cloud-platform

The error I get is written in my previous answer.

**Comment by MrBlaise** [comment]
Sorry I left most important part 
```
ecurityDefinitions:
  auth0_jwt:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://auth.redacted.com"
    x-google-jwks_uri: "https://auth.redacted.com/.well-known/jwks.json"
    x-google-audiences: "https://redacted.api"
```

The `https://auth.redacted.com` will fail with self signed error, when trying to authenticate the user.
