### ISSUE TITLE
Ability to pass headers from ESP to grpc backend

### ISSUE THREAD

**Issue by sgammon** [cloudendpoints/esp#323]
I don't see a way, documented or otherwise, to pass headers to gRPC similar to `proxy_set_header` in Nginx. I figured, perhaps, that all headers were transcoded to metadata, but that doesn't seem to be the case.

Is it possible to add a directive where we can set headers in the proxy, and see them in gRPC? For instance, if behavior in gRPC is based on source IP or some other transport value that isn't available without some headers?

I would be happy to contribute however I can. I'm running gRPC and ESP on Kubernetes in grpc-java.

**Comment by qiwzhang** [comment]
Hi @sgammon My understanding is: ESP should pass all client headers into gRPC metadata for  both gRPC client and HTTP client.  The code is here:  https://github.com/cloudendpoints/esp/blob/master/src/nginx/grpc.cc#L234

If that is NOT the case,  please help us debug it.

**Comment by lizan** [comment]
@qiwzhang I think what @sgammon try to do is to insert a header by ESP, which is not sent by client.

@sgammon I don't have time to work on this very soon. If you can contribute I'm happy to review though.

Some notes on implementation:
- Add a member to the location config `ngx_esp_loc_conf_t`, and parse it from nginx.conf
- The `ngx_esp_loc_conf_t` is extracted for gRPC here: https://github.com/cloudendpoints/esp/blob/master/src/nginx/grpc.cc#L154 
- Add the headers to https://github.com/cloudendpoints/esp/blob/master/src/nginx/grpc.cc#L174

**Comment by emicklei** [comment]
@sgammon can you confirm the statement of @qiwzhang saying "ESP should pass all client headers into gRPC metadata for both gRPC client and HTTP client."  
We have an issue passing our custom headers such "ctx_locale" ; this is absent in our gRPC server.

**Comment by emicklei** [comment]
hi, we found this issue. 
Because the custom headers included and underscore "_" in their name was the reason it was not passed.

**Comment by liam-j-bennett** [comment]
Has there been any progress on this? I'm looking for a way to send on the real IP of the remote client to gRPC using esp (similar to ```proxy_set_header X-Real-IP $remote_addr;``` for non-grpc). Wouldn't mind contributing, but can't say I'm very familar with nginx.

**Comment by qiwzhang** [comment]
Ideally,  ESP should support "proxy_set_header" flag for grpc backend to set any Nginx variables into grpc metadata. 

Unfortunately, There is no much progress in this feature.

**Comment by lucemia** [comment]
https://github.com/cloudendpoints/esp/pull/384#discussion_r183524675

Just need to pass in a --underscores_in_headers flag. 😀

**Comment by lucemia** [comment]
```
kubectl edit deployment gnlp-0-1-5-3  

...
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gnlp-0-1-5-3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gnlp-0-1-5-3
    spec:
      containers:
      - args:
        - --http2_port=9000
        - --service=gnlp.endpoints.living-bio.cloud.goog
        - --rollout_strategy=managed
        - --backend=grpc://127.0.0.1:80
        - --underscores_in_headers
        image: gcr.io/endpoints-release/endpoints-runtime:1
        imagePullPolicy: IfNotPresent
        name: esp
        ports:
        - containerPort: 9000
          protocol: TCP
...
```
