### ISSUE TITLE
ESP / Service Control does not validate IAM policies

### ISSUE THREAD

**Issue by FranOis** [cloudendpoints/esp#332]
I've setup my swagger definition for securing the entire API with Google ID JWT.

```
security: 
  - google_id_token: []
```

```
securityDefinitions: 
  google_id_token:
    authorizationUrl: ""
    type: "oauth2"
    flow: "implicit"
    x-google-issuer: "https://accounts.google.com"
```

I also have setup some policies on my Endpoint so that only one service account is `roles/servicemanagement.serviceConsumer`. When i make an authenticated call with any service account even from other GCP projects/ organizations, it seems like there is no validation beyond that the JWT is properly signed.

Looking at the code, it seems like this might only be enforced if I use an API Key which seems a bit redundant.
