### ISSUE TITLE
SSL passthough

### ISSUE THREAD

**Issue by ChrisTerBeke** [cloudendpoints/esp#350]
Right now there is no option to call the backend service over https? I'm using cloud endpoints in combination with an nginx ingress controller in k8s as backend, and I only want to allow https connections on that (since we also use that same controller for websockets on a different port). Is there a way to enable passthrough when the incoming request is https?

**Comment by qiwzhang** [comment]
It is supported.  Please look at this flag https://github.com/cloudendpoints/endpoints-tools/blob/master/start_esp/start_esp.py#L445

**Comment by ChrisTerBeke** [comment]
Awesome! Any plans on adding some docs for this? It's completely unfindable, even when using Google search.

**Comment by ChrisTerBeke** [comment]
Mm doesn't seem to work in my setup. This is the args section of my k8s config:

``` yaml
args: [
          "--http_port=8080",
          "--ssl_port=443",
          "--backend=127.0.0.1:444",
          "--tls_mutual_auth",
          "--enable_websocket",
          "--service=staging.endpoints.stardust-193112.cloud.goog",
          "--version=2018-02-05r1",
        ]
```

Any suggestions?

**Comment by ChrisTerBeke** [comment]
I'm now using `--enable_websocket` with success, which means I can do full TLS termination in ESP so I don't need the pass through anymore (which doesn't seem to work as specified in the limited documentation?).

Also the `--service_config_url` parameter doesn't seem to work properly (always getting a config error, even though the specified config is the same as the one deployed to GCP endpoints.

**Comment by bootstraponline** [comment]
```yaml
containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--ssl_port=9000",
          "--tls_mutual_auth",
          "--service=...",
          "--rollout_strategy=managed",
          "--backend=grpc://127.0.0.1:50051"
        ]
```

I have TLS mutual auth working on `esp` using an insecure gRPC server. ESP is doing SSL termination. Is there a way of enabling SSL passthrough so the communication between ESP and the gRPC server is secure?

**Comment by ChrisTerBeke** [comment]
@bootstraponline I would use different certs on your internal services to secure them.

**Comment by bootstraponline** [comment]
> @bootstraponline I would use different certs on your internal services to secure them.

Agreed, I am using the [cfssl](https://github.com/bootstraponline/grpc_java_auth/blob/master/soseedygrpc/openssl/cfssl.sh) library combined with a kubernetes volume mount which uploads the secret certs.

---

SSL passthrough does **not** work. I have a complete example [in this repo](https://github.com/bootstraponline/grpc_java_auth/pull/4). SSL termination on the load balancer works. SSL passthrough doesn't.

I'm hoping by providing working code, this makes life easier for future customers. The documentation lacks examples of gRPC SSL on cloud endpoints. If anyone has any idea on how to enable passthrough, let me know. A working simple code example is even better.

> Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 000012040000000000000300000080000400010000000500ffffff0000040800000000007fff00000000080700000000000000000000000001


```yaml
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http2_port=9000",
          "--service=echo.endpoints.delta-essence-114723.cloud.goog",
          "--rollout_strategy=managed",
          "--backend=grpc://127.0.0.1:50051"
        ]
        ports:
          - containerPort: 9000
      - name: passthrough
        image: gcr.io/delta-essence-114723/ssl_passthrough:latest
        ports:
          - containerPort: 50051
```

```kotlin
    @Test
    fun testClientConnects() {
        val client = MutualAuthClientTls
        val address = InetSocketAddress("35.224.8.72", 80)

        Truth.assertThat(client.runClient(address))
                .isEqualTo("world")
    }
```
