### ISSUE TITLE
Setup and Check oauth scopes

### ISSUE THREAD

**Issue by arturgspb** [cloudendpoints/esp#448]
Hi!

I work with Google Cloud Endpoint in local Kubernates cluster.
In setup GRPC + Transcoding I wrote access_token check with Google Service Account.
The token is issued by my internal service and the scope names are different there.
I wrote my custom canonical_scopes.

```yaml
type: google.api.Service
config_version: 3

name: myserviceendpoints.myproject.cloud.goog
title: myserviceapis.myproject
apis:
- name: myproject.hello.v1.Hello
- name: myproject.hello.v2.Hello

documentation:
  summary: |-
    Hello API for tests and examples.

usage:
  rules:
  - selector: "*"
    allow_unregistered_calls: true

authentication:
  providers:
  - id: google_service_account
    issuer: "token-issuer.myproject.io"
    audiences: "apis.myproject.io"
    jwks_uri: "https://www.googleapis.com/service_accounts/v1/jwk/token-issuer@myproject.iam.gserviceaccount.com"
  rules:
  - selector: "*"
    oauth:
      canonical_scopes: |-
       myscope
    requirements:
      - provider_id: google_service_account
```

On run gcloud endpoints services deploy I has error
```
ERROR: (gcloud.endpoints.services.deploy) INVALID_ARGUMENT: Cannot convert to service config.
 'ERROR: v1/hello.proto:20:5: auth: canonical_scopes has unknown scope 'myscope'.
```

If I install Google's scopes, the ESP still does not give an error of access to the api method without the necessary scopes. The token is issued by my internal service and the scope names are different there.

```
      canonical_scopes: |-
        https://www.googleapis.com/auth/bigtable.data,
        https://www.googleapis.com/auth/cloud-bigtable.data,
        https://www.googleapis.com/auth/cloud-platform
```

Can you tell me if ESP can do access control by scopes on methods on its side or should it be checked directly in your application code? I didn't find this in the documentation Google Cloud Endpoints.

Thanks in advance for the answer!
