### ISSUE TITLE
Issues making calls to a gRPC service on GKE (Cloud Endpoints & ESP) from browser (grpc-web)

### ISSUE THREAD

**Issue by diericx** [cloudendpoints/esp#640]
**Intro to the issue**
I have a gRPC service that is running in GKE. I'm using Cloud Endpoints and have an ESP (Extensible Service Proxy) in front of it that I want to use to handle authentication (JWT tokens).

This sounds like a really great way to integrate all these tools together, but for the past 2 days I haven't been able to get this working. I can connect and make calls perfectly when running locally, but going through the ESP has proven to be pretty difficult to setup.

_Note: I eventually want to open up an http2 port, but my focus right now is getting browser support so I'm just opening the http port_

**The K8s deployment and service config**
My service is running and working, and I am deploying it with this manifest

```
apiVersion: v1
kind: Service
metadata:
  name: esp-grpc-environment
spec:
  ports:
  # Port that accepts gRPC and JSON/HTTP2 requests over HTTP.
  - port: 80
    targetPort: 9090
    protocol: TCP
    name: http2
  selector:
    app: esp-grpc-environment
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esp-grpc-environment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: esp-grpc-environment
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http_port=9090",
          "--service=environment.endpoints.olamai-d64a7.cloud.goog",
          "--rollout_strategy=managed",
          "--backend=grpc://127.0.0.1:8000",
          "--cors_preset=basic",
          "--cors_allow_headers=Keep-Alive,User-Agent,Cache-Control,Content-Type,Content-Transfer-Encoding,X-Accept-Content-Transfer-Encoding,X-Accept-Response-Streaming,X-User-Agent,X-Grpc-Web,Grpc-Timeout,Authorization,authorization",
          "--cors_expose_headers=grpc-status,grpc-message,authorization",
          "--enable_debug"
        ]
        ports:
          - containerPort: 9090
      - name: environment
        image: terrariumai/environment:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
```

So I was originally just using my own nginx proxy but decided I wanted the features of Endpoints. With this and a lot of errors, I got all of the Cors arguments for the ESP.

And here is the config with the auth settings

```
type: google.api.Service
config_version: 3

name: environment.endpoints.<project id>.cloud.goog
title: Environment gRPC API

apis:
  - name: endpoints.terrariumai.environment.Environment

authentication:
  providers:
    - id: firebase
      jwks_uri: https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com
      issuer: https://securetoken.google.com/<project-id>
  rules:
    - selector: "*"
      requirements:
        - provider_id: firebase

usage:
  rules:
    - selector: endpoints.terrariumai.environment.Environment.CreateEntity
      allow_unregistered_calls: true
```

[I was also asked to post my service config, here is a link to a gist of it as it is super long.](https://gist.github.com/diericx/683f275b82315cbe725f447c8fa2975c)

**Making calls to the service with Node/React**
So once this is running and deployed, I use my React app to hit the service like this

import {
  CreateEntityRequest
} from "../api/environment_pb";

```
this.props.firebase
      .auth()
      .currentUser.getIdToken(/* forceRefresh */ true)
      .then(function(idToken) {
        var service = new EnvironmentClient(addr, null, null);
        var request = new CreateEntityRequest();
        var metadata = {
          authorization: `Bearer ${idToken}`
        };
        console.log(idToken);
        service.createEntity(request, metadata, (err, resp) => {
          if (err) {
            console.log("Got error: ", err);
          }
          console.log("Resp: ", resp);
        });
      })
```

And from this, I get this error
`POST http://<external-ip>/endpoints.terrariumai.environment.Environment/CreateEntity 403 (Forbidden)`

Here is all that is in /var/log/nginx/error.log

```
2019/07/11 00:06:44 [debug] 9#9: *8 HTTP/1.1 403 Forbidden
Server: nginx
Date: Thu, 11 Jul 2019 00:06:44 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
WWW-Authenticate: Bearer, error="invalid_token"
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
Access-Control-Allow-Headers: Keep-Alive,User-Agent,Cache-Control,Content-Type,Content-Transfer-Encoding,X-Accept-Content-Transfer-Encoding,X-Accept-Response-Streaming,X-User-Agent,X-Grpc-Web,Grpc-Timeout,Authorization,authorization
Access-Control-Expose-Headers: grpc-status,grpc-message,authorization

2019/07/11 00:06:44 [debug] 9#9: *8 write new buf t:1 f:0 000056541D4E9778, pos 000056541D4E9778, size: 618 file: 0, size: 0
2019/07/11 00:06:44 [debug] 9#9: *8 http write filter: l:0 f:0 s:618
2019/07/11 00:06:44 [debug] 9#9: *8 http output filter "/endpoints.terrariumai.environment.Environment/CreateEntity?"
2019/07/11 00:06:44 [debug] 9#9: *8 ESP error message: JWT validation failed: Audience not allowed
2019/07/11 00:06:44 [debug] 9#9: *8 send error response: {
 "code": 7,
 "message": "JWT validation failed: Audience not allowed",
 "details": [
  {
   "@type": "type.googleapis.com/google.rpc.DebugInfo",
   "stackEntries": [],
   "detail": "auth"
  }
 ]
}
```

It looks like this may be an issue with the audience. Not sure what that means.
Edit: I just found this log (I had set the debug setting wrong) so I'm looking into this right now

`[09/Jul/2019:20:40:49 +0000] "POST /endpoints.terrariumai.environment.Environment/CreateEntity HTTP/1.1" 403 210 "http://localhost:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"`

To me, it seems like the ESP is refusing the calls and saying they are forbidden (maybe not authenticated??). But at this point I'm stumped. I really don't know where to look further. I would appreciate any help and can provide any more information if it's necessary!

**Comment by diericx** [comment]
After looking further into the logs it seems like it's an audience issue with the JWT. I'm not exactly sure what that means, but from reading it seems like the audience in the JWT needs to match the service name of the ESP. I'm not sure if its possible to set the aud with firebase when generating a JWT, but I my client-id to the audiences in the ESP config which didn't work.

**Comment by diericx** [comment]
I ended up just making REST calls instead of using grpc-web this was giving me too much of a headache

**Comment by qiwzhang** [comment]
@diericx You can set your own "audience" in the Service config.  Here is the [instruction](https://cloud.google.com/endpoints/docs/grpc/authenticating-users) for Firebase

**Comment by jackwootton** [comment]
@qiwzhang the documentation you linked states `audience` is optional, yet this fails with `JWT validation failed: Audience not allowed`

**Comment by nareddyt** [comment]
Just to clarify:

- Optional as in you can completely omit the field `audiences`. Then ESP will not check it if it's omitted in the config. Have you tried omitting it to ensure ESP works then?
- Try adding `https://` as a prefix to all the values you tried and make sure to replace `YOUR-PROJECT-ID`

```
audiences: "https://myservice.endpoints.YOUR-PROJECT-ID.cloud.goog"
```

**Comment by qiwzhang** [comment]
What is the "aud" in your JWT?  That field has to match the one specified in the "audience" field in the service config.  The "audience" field is optional, if not specified, "aud" has to match the endpoint service name.   Multiple audiences can be specified separated by comma.

**Comment by jackwootton** [comment]
@nareddyt I decoded the authorization header https://jwt.io/ and `aud` was `my-project-id`. I then set this in my API condig, deployed the service and still it failed.

**Comment by jackwootton** [comment]
```yaml
# The schema of this file.
type: google.api.Service

# The version of the GRPC API Configurations.
config_version: 3

# The value for the title is displayed on your portal homepage in the
# section that lists the APIs in the project, the API homepage (with
# the word documentation appended to it), and in the API title bar.
title: My API (Local)

# The service name. It should be the primary DNS name for the service.
name: jsonschema.endpoints.YOUR-PROJECT-ID.cloud.goog

endpoints:
  # Below entry makes 'jsonschema.endpoints.json-schema.cloud.goog'
  # API be served from endpoint address jsonschema.endpoints.json-schema.cloud.goog.
  # It also allows HTTP OPTIONS calls to be passed to the backend, for
  # it to decide whether the subsequent cross-origin request is
  # allowed to proceed.
  - name: myservice.endpoints.YOUR-PROJECT-ID.cloud.goog
    allow_cors: true

authentication:
  providers:
  - id: firebase
    jwks_uri: https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com
    # Replace YOUR-PROJECT-ID with your project ID
    issuer: https://securetoken.google.com/json-schema-local
    # Optional. Replace YOUR-CLIENT-ID with your client ID
    audiences: YOUR-PROJECT-ID
  rules:
  - selector: "*"
    requirements:
      - provider_id: firebase
```
