### ISSUE TITLE
allowCors doesn't work for the backends by x-google-backend.

### ISSUE THREAD

**Issue by sulantha2006** [cloudendpoints/esp#737]
I am using ESP infront of Django Rest Framework. However, I use the OPTIONS call to get dynamic choices for the forms (foreign field related choices) 
After adding the ESP, I get a empty 204 response for all OPTIONS calls.

Is there a workaround for this or other best practices? Thanks.

**Comment by qiwzhang** [comment]
How do you setup CORS supports?  There are two ways:

1) if your backend HTTP server supports CORS,  setup ESP to pass through OPTIONS calls to your backend by following [this](https://cloud.google.com/endpoints/docs/openapi/openapi-extensions).

<pre>
x-google-endpoints:
- name: "API_NAME.endpoints.PROJECT_ID.cloud.goog"
  allowCors: True
</pre>

2) If your backend HTTP servier doesn't support CORS,  add CORS flags to ESP to  let ESP handle OPTIONS calls.  Follow this [link](https://cloud.google.com/endpoints/docs/openapi/specify-proxy-startup-options)

**Comment by sulantha2006** [comment]
I have support for CORS from backend: When I try accessing the API directly with OPTIONS, I get the correct response. 
But when accessing through the ESP, i get 204 empty response. 
I have allowCors:true in the config. 
Also note: i am using ESP with Cloud run. See the configuration below. 

```
x-google-endpoints:
- name: accounts-test-esp2-ncqyoyehtq-uc.a.run.app
  allowCors: true

x-google-backend:
  address: https://accounts-api-test-ncqyoyehtq-uc.a.run.app
```
