### ISSUE TITLE
unexpected timeout occurring (gRPC, GKE, cloudendpoints)

### ISSUE THREAD

**Issue by sbsends** [cloudendpoints/esp#781]
Hello 👋

While building a gRPC bidirectional streaming service on GKE / Cloud Endpoints we discovered an unexpected timeout. While testing the server locally, there is no timeout. However, when we try to keep an idle stream open on ESP / GKE there is a one minute timeout. We are unsure whether the timeout is stemming from the GKE loadbalancer or ESP so any methods of isolating this would also be extremely helpful!

Thank you!

# gRPC golang server code
```golang
grpcServer := grpc.NewServer()
defer grpcServer.GracefulStop()
```

# Kubernetes service config
```yaml
apiVersion: v1
kind: Service
metadata:
  name: quartet-service
spec:
  type: LoadBalancer
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
    name: http2
  selector:
    service: quartet-service
```
