### ISSUE TITLE
unexpected "h" in /etc/nginx/endpoints/nginx.conf

### ISSUE THREAD

**Issue by jsonsystems** [cloudendpoints/esp#786]
[CORS support in ESP](https://cloud.google.com/endpoints/docs/openapi/specify-proxy-startup-options#adding_cors_support_to_esp) seems broken.

`cors_allow_origin=*` works

```yaml
containers:
- args:
    - --http_port=8081
    - --backend=grpc://127.0.0.1:8080
    - --service=foo.endpoints.my-project.cloud.goog
    - --rollout_strategy=managed
    - --cors_preset=basic
    - --cors_allow_origin=*
    image: gcr.io/endpoints-release/endpoints-runtime:1
    name: esp
```

And `cors_allow_origin=https://example.com` breaks

```yaml
containers:
- args:
    - --http_port=8081
    - --backend=grpc://127.0.0.1:8080
    - --service=foo.endpoints.my-project.cloud.goog
    - --rollout_strategy=managed
    - --cors_preset=basic
    - --cors_allow_origin="https://example.com"
    image: gcr.io/endpoints-release/endpoints-runtime:1
    name: esp
```

The ESP container fails to start. The logs show:
```
textPayload: "nginx: [emerg] unexpected "h" in /etc/nginx/endpoints/nginx.conf:89"
```
