### ISSUE TITLE
Cannot refer to service name using x-google-backend

### ISSUE THREAD

**Issue by nrabinowitz** [cloudendpoints/esp#827]
I'm running ESP in GKE, following https://cloud.google.com/endpoints/docs/openapi/get-started-kubernetes-engine

I have a microservices architecture, with multiple services running in different containers in the cluster.

- When I deploy ESP with `--backend my-service-name:80`, endpoints are correctly routed to the service `my-service-name`.
- When I deploy ESP with `--enable_backend_routing` and include `x-google-backend` on a per-operation basis in my `openapi.yml`, so that I can route different operations to different backends, I can't seem to route properly with the service name. The IP address of the service works, but that's not a stable solution.

```
paths:
  "/v1/some-path":
    post:
      x-google-backend:
        address: "http://my-service-name:80"
        path_translation: APPEND_PATH_TO_ADDRESS
```
gives me 503 Bad Gateway in my requests, and `my-service-name could not be resolved (3: Host not found)` in my logs. The same setup with the IP address works, but as noted above it's not a solution.

Is there a way to route to the service by name on a per-operation basis?
