### ISSUE TITLE
x-google-jwt-location two entries for a single header

### ISSUE THREAD

**Issue by td-gonzales** [cloudendpoints/esp#850]
Given this configuration:
```
    x-google-jwt-locations:
      - header: "Authorization"
        value_prefix: "Bearer "
      - header: "Authorization"
         value_prefix: ""
```

I would expect passing the header with the "Bearer " prefix to work. However only one of the options works. It looks like you can only have one prefix per header. Is that expected behavior?
